config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :search do
    collection do
      get 'search_artist'
    end
  end

  # Defines the root path route ("/")
  root "search#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index

  end

  def search_artist
    response = SearchArtist.new(params[:query]).call

    if response.code == 200
      @results = response['response']['hits']
    else
      @results = []
      @error = "Error fetching results. Please try again."
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genius</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/_songs.html.erb
<% songs.each do |song| %>
  <div class="song-result">
    <h3><%= song["result"]["title"] %></h3>
  </div>
<% end %>

<% if songs.empty? and !error.present? %>
  <div class="no-results">
    <p>Artist not found.</p>
  </div>
<% end %>

<% if error.present? %>
  <div class="error-message">
    <p><%= error %></p>
  </div>
<% end %>

app/views/search/index.html.erb
<%= form_with(url: search_artist_search_index_path, method: :get, data: { turbo_frame: "songs_frame", turbo_stream: true }) do |form| %>
  <%= form.label :query, "Search Artist:" %>
  <%= form.text_field :query, placeholder: "Artist name" %>
  <%= form.submit "Search" %>
<% end %>


<%= turbo_frame_tag "songs_frame" do %>
<% end %>

app/views/search/search_artist.turbo_stream.erb
<%= turbo_stream.update "songs_frame" do %>
  <%= render 'songs', songs: @results || [], error: @error %>
<% end %>